package com.project.farmnode.mapper;


import com.project.farmnode.dto.PostResponse;
import com.project.farmnode.dto.ProduceDto;
import com.project.farmnode.model.Post;
import com.project.farmnode.model.Produce;
import com.project.farmnode.model.User;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public abstract class ProduceMapper {
    @Mapping(target = "produceId", ignore = true) //autogenerated
    @Mapping(target = "produceName", source = "produceDto.produceName")
    @Mapping(target = "user", source = "user")
    public abstract Produce map(ProduceDto produceDto, User user);

    @Mapping(target = "produceId", source = "produceId")
    @Mapping(target = "userName", source = "user.username")
    /*@Mapping(target = "commentCount", expression = "java(commentCount(post))")
    @Mapping(target = "duration", expression = "java(getDuration(post))")
    @Mapping(target = "upVote", expression = "java(isPostUpVoted(post))")
    @Mapping(target = "downVote", expression = "java(isPostDownVoted(post))")*/
    public abstract ProduceDto mapToDto(Produce produce);
}
