package com.project.farmnode.mapper;


import com.project.farmnode.dto.ProduceDto;
import com.project.farmnode.model.Post;
import com.project.farmnode.model.Produce;
import com.project.farmnode.model.User;
import com.project.farmnode.repository.CommentRepo;
import com.project.farmnode.repository.ProduceCommentRepo;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.springframework.beans.factory.annotation.Autowired;

@Mapper(componentModel = "spring")
public abstract class ProduceMapper {

    @Autowired
    private ProduceCommentRepo produceCommentRepo;

    @Mapping(target = "produceId", ignore = true) //autogenerated
    @Mapping(target = "produceName", source = "produceDto.produceName")
    @Mapping(target = "filename", source = "produceDto.filename")
    @Mapping(target = "user", source = "user")
    public abstract Produce map(ProduceDto produceDto, User user);


    @Mapping(target = "produceName", source = "produceDto.produceName")
    @Mapping(target = "filename", source = "produceDto.filename")
    @Mapping(target = "user", source = "user")
    public abstract Produce mapUpdate(ProduceDto produceDto, User user);

    @Mapping(target = "produceId", source = "produceId")
    @Mapping(target = "userName", source = "user.username")
    @Mapping(target = "grower", source = "user.name")
    @Mapping(target = "measureType", source = "measureType")
    @Mapping(target = "filename", source = "filename")
    @Mapping(target = "commentCount", expression = "java(commentCount(produce))")
    /*@Mapping(target = "duration", expression = "java(getDuration(post))")
    @Mapping(target = "upVote", expression = "java(isPostUpVoted(post))")
    @Mapping(target = "downVote", expression = "java(isPostDownVoted(post))")*/
    public abstract ProduceDto mapToDto(Produce produce);

    Integer commentCount(Produce produce) {
        return produceCommentRepo.findByProduceOrderByCreatedDateDesc(produce).size();
    }

}
